stigma:
  image: stigma01
  links:
    - mysql
    - grafana
    - influxdb
  ports:
    - 22:22
    - 80:80
  volumes:
    - /docker-vol:/app
mysql:
  image: mysql01
  ports:
    - 3306:3306
  volumes:
    - /docker-vol:/app
grafana:
  image: grafana01
  ports:
    - 3000:3000
  volumes:
    - /docker-vol:/app
influxdb:
  image: influxdb01
  links:
    - grafana
  ports:
    - 8083:8083
    - 8086:8086
  volumes:
    - /docker-vol:/app
nagios:
  image: nagios01
  links:
    - influxdb
  ports:
    - 8080:80
  volumes:
    - /docker-vol:/app
